### ISSUE TITLE
How to execute in Mac OSX

### ISSUE THREAD

**Issue by quest** [DMoneigh/PlayStation-Network-Sniffer#1]
Hello,

I tried with Maven, but not working. Can u show me the commandos for execute in my terminal?

Thanks.

**Comment by DMoneigh** [comment]
Hello quest,

Assuming that you have already installed libcap for MAC, you should be able to type the "list" and "get [username]" commands into terminal.

For PS4 no usernames should appear, only IP addresses (due to Sony's patch).
For PS3 usernames should appear next to IP addresses.

I have not looked at any packet traffic from PlayStation since early March, so there could also be a possibility that there has been a change in packet data.

Thanks,
DMoneigh
